
include /commun/data/packages/tools.mk


GTF=/commun/data/pubdb/ucsc/mm10

INDIR=../align/merged.bam
OUTDIR=../align/cufflinks


PHONY=all clean


all:  ${OUTDIR}/30VGKM1/transcripts.gtf  ${OUTDIR}/30VGKM2/transcripts.gtf  ${OUTDIR}/30VGKM3/transcripts.gtf  ${OUTDIR}/30VGKS1/transcripts.gtf  ${OUTDIR}/30VGKS2/transcripts.gtf  ${OUTDIR}/30VGKS3/transcripts.gtf  ${OUTDIR}/30VGWT1/transcripts.gtf  ${OUTDIR}/30VGWT3/transcripts.gtf  ${OUTDIR}/45VGKM1/transcripts.gtf  ${OUTDIR}/45VGKM2/transcripts.gtf  ${OUTDIR}/45VGKS1/transcripts.gtf  ${OUTDIR}/45VGKS2/transcripts.gtf  ${OUTDIR}/45VGKS3/transcripts.gtf  ${OUTDIR}/45VGWT1/transcripts.gtf  ${OUTDIR}/45VGWT2/transcripts.gtf  ${OUTDIR}/45VGWT3/transcripts.gtf  ${OUTDIR}/6VGKM1/transcripts.gtf  ${OUTDIR}/6VGKM2/transcripts.gtf  ${OUTDIR}/6VGKM3/transcripts.gtf  ${OUTDIR}/6VGKS1/transcripts.gtf  ${OUTDIR}/6VGKS2/transcripts.gtf  ${OUTDIR}/6VGWT1/transcripts.gtf  ${OUTDIR}/6VGWT2/transcripts.gtf  ${OUTDIR}/6VGWT3/transcripts.gtf ${OUTDIR}/30VGWT2/transcripts.gtf  ${OUTDIR}/45VGKM3/transcripts.gtf  ${OUTDIR}/6VGKS3/transcripts.gtf 

${OUTDIR}/30VGKM1/transcripts.gtf: ${INDIR}/30VGKM1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGKM1 ${INDIR}/30VGKM1.bam

${OUTDIR}/30VGKM2/transcripts.gtf: ${INDIR}/30VGKM2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGKM2 ${INDIR}/30VGKM2.bam

${OUTDIR}/30VGKM3/transcripts.gtf: ${INDIR}/30VGKM3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGKM3 ${INDIR}/30VGKM3.bam

${OUTDIR}/30VGKS1/transcripts.gtf: ${INDIR}/30VGKS1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGKS1 ${INDIR}/30VGKS1.bam

${OUTDIR}/30VGKS2/transcripts.gtf: ${INDIR}/30VGKS2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGKS2 ${INDIR}/30VGKS2.bam

${OUTDIR}/30VGKS3/transcripts.gtf: ${INDIR}/30VGKS3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGKS3 ${INDIR}/30VGKS3.bam

${OUTDIR}/30VGWT1/transcripts.gtf: ${INDIR}/30VGWT1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGWT1 ${INDIR}/30VGWT1.bam

${OUTDIR}/30VGWT3/transcripts.gtf: ${INDIR}/30VGWT3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGWT3 ${INDIR}/30VGWT3.bam

${OUTDIR}/45VGKM1/transcripts.gtf: ${INDIR}/45VGKM1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGKM1 ${INDIR}/45VGKM1.bam

${OUTDIR}/45VGKM2/transcripts.gtf: ${INDIR}/45VGKM2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGKM2 ${INDIR}/45VGKM2.bam

${OUTDIR}/45VGKS1/transcripts.gtf: ${INDIR}/45VGKS1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGKS1 ${INDIR}/45VGKS1.bam

${OUTDIR}/45VGKS2/transcripts.gtf: ${INDIR}/45VGKS2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGKS2 ${INDIR}/45VGKS2.bam

${OUTDIR}/45VGKS3/transcripts.gtf: ${INDIR}/45VGKS3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGKS3 ${INDIR}/45VGKS3.bam

${OUTDIR}/45VGWT1/transcripts.gtf: ${INDIR}/45VGWT1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGWT1 ${INDIR}/45VGWT1.bam

${OUTDIR}/45VGWT2/transcripts.gtf: ${INDIR}/45VGWT2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGWT2 ${INDIR}/45VGWT2.bam

${OUTDIR}/45VGWT3/transcripts.gtf: ${INDIR}/45VGWT3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGWT3 ${INDIR}/45VGWT3.bam

${OUTDIR}/6VGKM1/transcripts.gtf: ${INDIR}/6VGKM1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGKM1 ${INDIR}/6VGKM1.bam

${OUTDIR}/6VGKM2/transcripts.gtf: ${INDIR}/6VGKM2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGKM2 ${INDIR}/6VGKM2.bam

${OUTDIR}/6VGKM3/transcripts.gtf: ${INDIR}/6VGKM3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGKM3 ${INDIR}/6VGKM3.bam

${OUTDIR}/6VGKS1/transcripts.gtf: ${INDIR}/6VGKS1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGKS1 ${INDIR}/6VGKS1.bam

${OUTDIR}/6VGKS2/transcripts.gtf: ${INDIR}/6VGKS2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGKS2 ${INDIR}/6VGKS2.bam

${OUTDIR}/6VGWT1/transcripts.gtf: ${INDIR}/6VGWT1.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGWT1 ${INDIR}/6VGWT1.bam

${OUTDIR}/6VGWT2/transcripts.gtf: ${INDIR}/6VGWT2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGWT2 ${INDIR}/6VGWT2.bam

${OUTDIR}/6VGWT3/transcripts.gtf: ${INDIR}/6VGWT3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGWT3 ${INDIR}/6VGWT3.bam


${OUTDIR}/30VGWT2/transcripts.gtf: ${INDIR}/30VGWT2.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/30VGWT2 ${INDIR}/30VGWT2.bam


${OUTDIR}/45VGKM3/transcripts.gtf: ${INDIR}/45VGKM3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/45VGKM3 ${INDIR}/45VGKM3.bam


${OUTDIR}/6VGKS3/transcripts.gtf: ${INDIR}/6VGKS3.bam
	mkdir -p ${OUTDIR} && \
	${CUFFLINKS.dir}/cufflinks -p 20 -o ${OUTDIR}/6VGKS3 ${INDIR}/6VGKS3.bam





