

include /commun/data/packages/tools.mk
FASTQC=$(packages.dir)/FastQC/fastqc

GTF=/commun/data/pubdb/ucsc/mm10

INDIR=../align/merged.bam


PHONY=all clean




all:  ${INDIR}/30VGKM1.bai  ${INDIR}/30VGKM2.bai  ${INDIR}/30VGKM3.bai  ${INDIR}/30VGKS1.bai  ${INDIR}/30VGKS2.bai  ${INDIR}/30VGKS3.bai  ${INDIR}/30VGWT1.bai  ${INDIR}/30VGWT3.bai  ${INDIR}/45VGKM1.bai  ${INDIR}/45VGKM2.bai  ${INDIR}/45VGKS1.bai  ${INDIR}/45VGKS2.bai  ${INDIR}/45VGKS3.bai  ${INDIR}/45VGWT1.bai  ${INDIR}/45VGWT2.bai  ${INDIR}/45VGWT3.bai  ${INDIR}/6VGKM1.bai  ${INDIR}/6VGKM2.bai  ${INDIR}/6VGKM3.bai  ${INDIR}/6VGKS1.bai  ${INDIR}/6VGKS2.bai  ${INDIR}/6VGWT1.bai  ${INDIR}/6VGWT2.bai  ${INDIR}/6VGWT3.bai 




${INDIR}/30VGKM1.bai:  ${INDIR}/30VGKM1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/30VGKM1.bam.bai ${INDIR}/30VGKM1.bai

${INDIR}/30VGKM2.bai:  ${INDIR}/30VGKM2.bam
	${SAMTOOLS} index $< && mv ${INDIR}/30VGKM2.bam.bai ${INDIR}/30VGKM2.bai

${INDIR}/30VGKM3.bai:  ${INDIR}/30VGKM3.bam
	${SAMTOOLS} index $< && mv ${INDIR}/30VGKM3.bam.bai ${INDIR}/30VGKM3.bai

${INDIR}/30VGKS1.bai:  ${INDIR}/30VGKS1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/30VGKS1.bam.bai ${INDIR}/30VGKS1.bai

${INDIR}/30VGKS2.bai:  ${INDIR}/30VGKS2.bam
	${SAMTOOLS} index $< && mv ${INDIR}/30VGKS2.bam.bai ${INDIR}/30VGKS2.bai

${INDIR}/30VGKS3.bai:  ${INDIR}/30VGKS3.bam
	${SAMTOOLS} index $< && mv ${INDIR}/30VGKS3.bam.bai ${INDIR}/30VGKS3.bai

${INDIR}/30VGWT1.bai:  ${INDIR}/30VGWT1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/30VGWT1.bam.bai ${INDIR}/30VGWT1.bai

${INDIR}/30VGWT3.bai:  ${INDIR}/30VGWT3.bam
	${SAMTOOLS} index $< && mv ${INDIR}/30VGWT3.bam.bai ${INDIR}/30VGWT3.bai

${INDIR}/45VGKM1.bai:  ${INDIR}/45VGKM1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/45VGKM1.bam.bai ${INDIR}/45VGKM1.bai

${INDIR}/45VGKM2.bai:  ${INDIR}/45VGKM2.bam
	${SAMTOOLS} index $< && mv ${INDIR}/45VGKM2.bam.bai ${INDIR}/45VGKM2.bai

${INDIR}/45VGKS1.bai:  ${INDIR}/45VGKS1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/45VGKS1.bam.bai ${INDIR}/45VGKS1.bai

${INDIR}/45VGKS2.bai:  ${INDIR}/45VGKS2.bam
	${SAMTOOLS} index $< && mv ${INDIR}/45VGKS2.bam.bai ${INDIR}/45VGKS2.bai

${INDIR}/45VGKS3.bai:  ${INDIR}/45VGKS3.bam
	${SAMTOOLS} index $< && mv ${INDIR}/45VGKS3.bam.bai ${INDIR}/45VGKS3.bai

${INDIR}/45VGWT1.bai:  ${INDIR}/45VGWT1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/45VGWT1.bam.bai ${INDIR}/45VGWT1.bai

${INDIR}/45VGWT2.bai:  ${INDIR}/45VGWT2.bam
	${SAMTOOLS} index $< && mv ${INDIR}/45VGWT2.bam.bai ${INDIR}/45VGWT2.bai

${INDIR}/45VGWT3.bai:  ${INDIR}/45VGWT3.bam
	${SAMTOOLS} index $< && mv ${INDIR}/45VGWT3.bam.bai ${INDIR}/45VGWT3.bai

${INDIR}/6VGKM1.bai:  ${INDIR}/6VGKM1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/6VGKM1.bam.bai ${INDIR}/6VGKM1.bai

${INDIR}/6VGKM2.bai:  ${INDIR}/6VGKM2.bam
	${SAMTOOLS} index $< && mv ${INDIR}/6VGKM2.bam.bai ${INDIR}/6VGKM2.bai

${INDIR}/6VGKM3.bai:  ${INDIR}/6VGKM3.bam
	${SAMTOOLS} index $< && mv ${INDIR}/6VGKM3.bam.bai ${INDIR}/6VGKM3.bai

${INDIR}/6VGKS1.bai:  ${INDIR}/6VGKS1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/6VGKS1.bam.bai ${INDIR}/6VGKS1.bai

${INDIR}/6VGKS2.bai:  ${INDIR}/6VGKS2.bam
	${SAMTOOLS} index $< && mv ${INDIR}/6VGKS2.bam.bai ${INDIR}/6VGKS2.bai

${INDIR}/6VGWT1.bai:  ${INDIR}/6VGWT1.bam
	${SAMTOOLS} index $< && mv ${INDIR}/6VGWT1.bam.bai ${INDIR}/6VGWT1.bai

${INDIR}/6VGWT2.bai:  ${INDIR}/6VGWT2.bam
	${SAMTOOLS} index $< && mv ${INDIR}/6VGWT2.bam.bai ${INDIR}/6VGWT2.bai

${INDIR}/6VGWT3.bai:  ${INDIR}/6VGWT3.bam
	${SAMTOOLS} index $< && mv ${INDIR}/6VGWT3.bam.bai ${INDIR}/6VGWT3.bai

