
include /commun/data/packages/tools.mk
FASTQC=$(packages.dir)/FastQC/fastqc

GTF=/commun/data/pubdb/ucsc/mm10

INDIR=../fastqrnaseq/Project_RNAseqSCN5A/fastqcutadapt-a
OUTDIR=../align


PHONY=all clean



all:  ${OUTDIR}/merged.bam/30VGKM1.bam  ${OUTDIR}/merged.bam/30VGKM2.bam  ${OUTDIR}/merged.bam/30VGKM3.bam  ${OUTDIR}/merged.bam/30VGKS1.bam  ${OUTDIR}/merged.bam/30VGKS2.bam  ${OUTDIR}/merged.bam/30VGKS3.bam  ${OUTDIR}/merged.bam/30VGWT1.bam  ${OUTDIR}/merged.bam/30VGWT3.bam  ${OUTDIR}/merged.bam/45VGKM1.bam  ${OUTDIR}/merged.bam/45VGKM2.bam  ${OUTDIR}/merged.bam/45VGKS1.bam  ${OUTDIR}/merged.bam/45VGKS2.bam  ${OUTDIR}/merged.bam/45VGKS3.bam  ${OUTDIR}/merged.bam/45VGWT1.bam  ${OUTDIR}/merged.bam/45VGWT2.bam  ${OUTDIR}/merged.bam/45VGWT3.bam  ${OUTDIR}/merged.bam/6VGKM1.bam  ${OUTDIR}/merged.bam/6VGKM2.bam  ${OUTDIR}/merged.bam/6VGKM3.bam  ${OUTDIR}/merged.bam/6VGKS1.bam  ${OUTDIR}/merged.bam/6VGKS2.bam  ${OUTDIR}/merged.bam/6VGWT1.bam  ${OUTDIR}/merged.bam/6VGWT2.bam  ${OUTDIR}/merged.bam/6VGWT3.bam 
${OUTDIR}/merged.bam/30VGKM1.bam: $(wildcard ${OUTDIR}/tophat/30VGKM1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/30VGKM2.bam: $(wildcard ${OUTDIR}/tophat/30VGKM2*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/30VGKM3.bam: $(wildcard ${OUTDIR}/tophat/30VGKM3*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/30VGKS1.bam: $(wildcard ${OUTDIR}/tophat/30VGKS1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/30VGKS2.bam: $(wildcard ${OUTDIR}/tophat/30VGKS2*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/30VGKS3.bam: $(wildcard ${OUTDIR}/tophat/30VGKS3*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/30VGWT1.bam: $(wildcard ${OUTDIR}/tophat/30VGWT1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/30VGWT3.bam: $(wildcard ${OUTDIR}/tophat/30VGWT3*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/45VGKM1.bam: $(wildcard ${OUTDIR}/tophat/45VGKM1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/45VGKM2.bam: $(wildcard ${OUTDIR}/tophat/45VGKM2*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/45VGKS1.bam: $(wildcard ${OUTDIR}/tophat/45VGKS1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/45VGKS2.bam: $(wildcard ${OUTDIR}/tophat/45VGKS2*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/45VGKS3.bam: $(wildcard ${OUTDIR}/tophat/45VGKS3*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/45VGWT1.bam: $(wildcard ${OUTDIR}/tophat/45VGWT1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/45VGWT2.bam: $(wildcard ${OUTDIR}/tophat/45VGWT2*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/45VGWT3.bam: $(wildcard ${OUTDIR}/tophat/45VGWT3*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/6VGKM1.bam: $(wildcard ${OUTDIR}/tophat/6VGKM1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/6VGKM2.bam: $(wildcard ${OUTDIR}/tophat/6VGKM2*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/6VGKM3.bam: $(wildcard ${OUTDIR}/tophat/6VGKM3*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/6VGKS1.bam: $(wildcard ${OUTDIR}/tophat/6VGKS1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/6VGKS2.bam: $(wildcard ${OUTDIR}/tophat/6VGKS2*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/6VGWT1.bam: $(wildcard ${OUTDIR}/tophat/6VGWT1*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/6VGWT2.bam: $(wildcard ${OUTDIR}/tophat/6VGWT2*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^
${OUTDIR}/merged.bam/6VGWT3.bam: $(wildcard ${OUTDIR}/tophat/6VGWT3*/accepted_hits.bam)
	mkdir -p ${OUTDIR}/merged.bam && \
	${SAMTOOLS} merge $@ $^







